### ISSUE TITLE
Initial Set Up

### ISSUE THREAD

**Issue by Prestongeyer713** [Prestongeyer713/novid#1]
#Requirments
-establish feature branch 
-establish HTML outline to get websites structure, with a title search box and button and column to hold the map.
-apply base level styling connect a css format (thats not bootstrap)

**Comment by NGoody315** [comment]
Put the HTML with the search box and button, didn't make a column to hold the map .

**Comment by Prestongeyer713** [comment]
All good from what I understand we’ll be able to set that up with the JavaScript! Thanks for all your hard work!
